{
  "openapi": "3.0.3",
  "info": {
    "title": "LN Markets API",
    "description": "Trade derivatives on the **[Lightning Network](https://lightning.network/)**.\nYou can find our website **[here](https://lnmarkets.com/)**.\n",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "https://api.lnmarkets.com/v1",
      "description": "Mainnet API"
    },
    {
      "url": "https://api.testnet.lnmarkets.com/v1",
      "description": "Testnet API"
    }
  ],
  "tags": [
    {
      "name": "Login",
      "description": "Here you can find the different way to auth yourself on LN Markets, mostly use for browser."
    },
    {
      "name": "Futures",
      "description": "Interactions with the futures market."
    },
    {
      "name": "Options",
      "description": "Interactions with the options market."
    },
    {
      "name": "User",
      "description": "Interaction with your user data."
    },
    {
      "name": "App",
      "description": "LN Markets application information."
    },
    {
      "name": "LNURL",
      "description": "Interaction with the lightning network using the [LNURL procotocol](https://github.com/btcontract/lnurl-rfc/)\nLNURL enable simple auth, withdraw and pay UX / UI.\n"
    }
  ],
  "security": [
    {
      "apiKeyAuth": []
    }
  ],
  "components": {
    "securitySchemes": {
      "apiKeyAuth": {
        "description": "Api key auth is using `LNM-ACCESS-KEY` `LNM-ACCESS-PASSPHRASE` `LNM-ACCESS-TIMESTAMP` `LNM-ACCESS-SIGN` headers\n(Only one header is shown below because our docs engine does not allow to put more there)\nSee (here)[https://docs.lnmarkets.com/api/v1/#section/REST-API/Authentication]\n",
        "type": "apiKey",
        "in": "header",
        "name": "LNM-ACCESS-KEY"
      }
    }
  },
  "paths": {
    "/app/configuration": {
      "get": {
        "tags": [
          "App"
        ],
        "security": [],
        "summary": "Configuration",
        "description": "Retrieves the configuration of LN Markets"
      }
    },
    "/app/node": {
      "get": {
        "tags": [
          "App"
        ],
        "security": [],
        "deprecated": false,
        "summary": "Node",
        "description": "Shows information about the lightning node."
      }
    },
    "/futures/add-margin": {
      "post": {
        "tags": [
          "Futures"
        ],
        "security": [
          {
            "apiKeyAuth": [
              "positions_modify"
            ]
          }
        ],
        "deprecated": false,
        "summary": "Add margin",
        "description": "Add margin to a running position."
      }
    },
    "/futures/all/cancel": {
      "delete": {
        "tags": [
          "Futures"
        ],
        "security": [
          {
            "apiKeyAuth": [
              "positions_close"
            ]
          }
        ],
        "deprecated": false,
        "summary": "Cancel-all",
        "description": "Cancel all open positions"
      }
    },
    "/futures/all/close": {
      "delete": {
        "tags": [
          "Futures"
        ],
        "security": [
          {
            "apiKeyAuth": [
              "positions_close"
            ]
          }
        ],
        "deprecated": false,
        "summary": "Close-all",
        "description": "Close every user position. The PL will be calculated against the current bid or offer\ndepending on the side of the position.\n"
      }
    },
    "/futures/cancel": {
      "post": {
        "tags": [
          "Futures"
        ],
        "security": [
          {
            "apiKeyAuth": [
              "positions_close"
            ]
          }
        ],
        "deprecated": false,
        "summary": "Cancel",
        "description": "Cancel the position linked to the given `pid`.**Only works on positions that are not currently filled**.\n"
      }
    },
    "/futures/carry-fees": {
      "get": {
        "tags": [
          "Futures"
        ],
        "security": [
          {
            "apiKeyAuth": [
              "positions_get_closed"
            ]
          }
        ],
        "summary": "Carry fees history",
        "description": "Retrieves carry fees for user"
      }
    },
    "/futures/cash-in": {
      "post": {
        "tags": [
          "Futures"
        ],
        "security": [
          {
            "apiKeyAuth": [
              "positions_modify"
            ]
          }
        ],
        "deprecated": false,
        "summary": "Cash-in",
        "description": "Retrieves part of one running positions PL.\n"
      }
    },
    "/futures": {
      "delete": {
        "tags": [
          "Futures"
        ],
        "security": [
          {
            "apiKeyAuth": [
              "positions_close"
            ]
          }
        ],
        "deprecated": false,
        "summary": "Close",
        "description": "Close the user position, the PL will be calculated against the current bid or offer\ndepending on the side of the position\n"
      },
      "get": {
        "tags": [
          "Futures"
        ],
        "security": [
          {
            "apiKeyAuth": [
              "positions_get_open",
              "positions_get_closed"
            ]
          }
        ],
        "deprecated": false,
        "summary": "Positions",
        "description": "Fetch users positions"
      },
      "post": {
        "tags": [
          "Futures"
        ],
        "security": [
          {
            "apiKeyAuth": [
              "positions_create"
            ]
          }
        ],
        "deprecated": false,
        "summary": "New position",
        "description": "Send the order form parameters to add a new position in database.\n**If `type=\"l\"`, the property `price` must be included in the request to know when the position should be filled.**\n**You can choose to use the margin or the quantity as a parameter, the other will be calculated with the one you chose**\n"
      },
      "put": {
        "tags": [
          "Futures"
        ],
        "security": [
          {
            "apiKeyAuth": [
              "positions_modify"
            ]
          }
        ],
        "deprecated": false,
        "summary": "Update",
        "description": "Allows user to modify `stoploss` or `takeprofit` parameters of an existing position.\n"
      }
    },
    "/futures/history/bid-offer": {
      "get": {
        "tags": [
          "Futures"
        ],
        "security": [],
        "summary": "Bid and offer history",
        "description": "Retrieves bid and offer at most 1000 entries between two given timestamps."
      }
    },
    "/futures/history/fixing": {
      "get": {
        "tags": [
          "Futures"
        ],
        "security": [],
        "summary": "Fixing history",
        "description": "Retrieves at most 1000 entries between two given timestamps"
      }
    },
    "/futures/history/index": {
      "get": {
        "tags": [
          "Futures"
        ],
        "security": [],
        "summary": "Index history",
        "description": "Retrieves index history at most 1000 entries between two given timestamps."
      }
    },
    "/futures/instrument": {
      "get": {
        "tags": [
          "Futures"
        ],
        "security": [],
        "summary": "Instrument",
        "description": "Retrieves the configuration related to futures trading on the platform"
      }
    },
    "/futures/leaderboard": {
      "get": {
        "tags": [
          "App"
        ],
        "security": [],
        "deprecated": false,
        "summary": "Leaderboard",
        "description": "Get the 10 first users by pl broke down by day/week/month/all-time\n"
      }
    },
    "/futures/ticker": {
      "get": {
        "tags": [
          "Futures"
        ],
        "security": [],
        "summary": "Ticker",
        "description": "Retrieves the futures ticker"
      }
    },
    "/lnurl/auth": {
      "get": {
        "tags": [
          "LNURL"
        ],
        "security": [],
        "deprecated": false,
        "summary": "Auth Verify",
        "description": "Verify the public key with the signature and the k1 to create a account or connect into a existing account.\nIf token is set to true, a token will be returned\nElse the connected state will be push over websockets the client\n"
      },
      "post": {
        "tags": [
          "LNURL"
        ],
        "security": [],
        "deprecated": false,
        "summary": "Auth Request",
        "description": "LNURL string used to create an account or connect to a existing account.\nThe user wallet will sign a message using the provided k1 inside the LNURL.\nYou need to have a session cookie on the browser you are using to log in.\n"
      }
    },
    "/lnurl/pay/address": {
      "get": {
        "tags": [
          "LNURL"
        ],
        "security": [],
        "deprecated": false,
        "summary": "Lightning Address",
        "description": "Lightning Address"
      }
    },
    "/lnurl/pay": {
      "get": {
        "tags": [
          "LNURL"
        ],
        "security": [],
        "deprecated": false,
        "summary": "Pay (3) Finalize",
        "description": "LNURL Pay"
      },
      "post": {
        "tags": [
          "LNURL"
        ],
        "security": [],
        "deprecated": false,
        "summary": "Pay (1) Create",
        "description": "Create a LNURL Pay"
      }
    },
    "/lnurl/pay/request": {
      "get": {
        "tags": [
          "LNURL"
        ],
        "security": [],
        "deprecated": false,
        "summary": "Pay (1) Request",
        "description": "Response from the LNURL"
      }
    },
    "/lnurl/withdraw/address": {
      "get": {
        "tags": [
          "LNURL"
        ],
        "security": [],
        "deprecated": false,
        "summary": "Withdraw to Lightning Address",
        "description": "Use Lightning Address to withdraw your sat !"
      }
    },
    "/lnurl/withdraw": {
      "get": {
        "tags": [
          "LNURL"
        ],
        "security": [],
        "deprecated": false,
        "summary": "Withdraw (3) Final",
        "description": "Use LNURL to withdraw from the user balance."
      },
      "post": {
        "tags": [
          "LNURL"
        ],
        "security": [],
        "deprecated": false,
        "summary": "Withdraw (1) Create",
        "description": "Create a LNURL Withdraw"
      }
    },
    "/lnurl/withdraw/request": {
      "get": {
        "tags": [
          "LNURL"
        ],
        "security": [],
        "deprecated": false,
        "summary": "Withdraw (2) Request",
        "description": "Ask the Lightning wallet to create an invoice with amount and description."
      }
    },
    "/options/instrument": {
      "get": {
        "tags": [
          "Options"
        ],
        "security": [],
        "summary": "Instrument",
        "description": "Get the options configuration"
      }
    },
    "/options/vanilla": {
      "delete": {
        "tags": [
          "Options"
        ],
        "security": [
          {
            "apiKeyAuth": [
              "vanilla_options_close"
            ]
          }
        ],
        "deprecated": false,
        "summary": "Close",
        "description": "Close the user option trade, the PL will be calculated against the current bid or offer\ndepending on the type of the option\n"
      },
      "get": {
        "tags": [
          "Options"
        ],
        "security": [
          {
            "apiKeyAuth": [
              "vanilla_options_get"
            ]
          }
        ],
        "deprecated": false,
        "summary": "Trades",
        "description": "Get user's vanilla options trades"
      },
      "post": {
        "tags": [
          "Options"
        ],
        "security": [
          {
            "apiKeyAuth": [
              "vanilla_options_order"
            ]
          }
        ],
        "deprecated": false,
        "summary": "New trade",
        "description": "Create a new options trade"
      }
    },
    "/options/volatility": {
      "get": {
        "tags": [
          "Options"
        ],
        "security": [],
        "deprecated": false,
        "summary": "Volatility",
        "description": "Return the volatility"
      }
    },
    "/user/deposit": {
      "get": {
        "tags": [
          "User"
        ],
        "security": [
          {
            "apiKeyAuth": [
              "wallet_deposit"
            ]
          }
        ],
        "deprecated": false,
        "summary": "Deposit History",
        "description": "Get deposit history"
      },
      "post": {
        "tags": [
          "User"
        ],
        "security": [
          {
            "apiKeyAuth": [
              "wallet_deposit"
            ]
          }
        ],
        "deprecated": false,
        "summary": "Deposit",
        "description": "Add fund to your LN Markets balance"
      }
    },
    "/user": {
      "get": {
        "tags": [
          "User"
        ],
        "security": [
          {
            "apiKeyAuth": [
              "user_get"
            ]
          }
        ],
        "deprecated": false,
        "summary": "Information",
        "description": "Get the user account Information"
      },
      "put": {
        "tags": [
          "User"
        ],
        "security": [
          {
            "apiKeyAuth": [
              "user_modify"
            ]
          }
        ],
        "deprecated": false,
        "summary": "Update user",
        "description": "Modifies account parameters"
      }
    },
    "/user/withdraw": {
      "get": {
        "tags": [
          "User"
        ],
        "security": [
          {
            "apiKeyAuth": [
              "wallet_withdraw"
            ]
          }
        ],
        "deprecated": false,
        "summary": "Withdraw History",
        "description": "Ge withdraw history\n"
      },
      "post": {
        "tags": [
          "User"
        ],
        "security": [
          {
            "apiKeyAuth": [
              "wallet_withdraw"
            ]
          }
        ],
        "summary": "Withdraw via invoice",
        "description": "Withdraw from LN Markets with a Lightning Invoice"
      }
    }
  }
}