{
  "openapi": "3.0.3",
  "info": {
    "title": "API",
    "description": "Trade derivatives on the **[Lightning Network](https://lightning.network/)**.\nYou can find our website **[here](https://lnmarkets.com/)**.\n",
    "version": "1.0.0"
  },
  "servers": [
    {
      "description": "Mainnet API",
      "url": "https://api.lnmarkets.com/v1"
    },
    {
      "description": "Testnet API",
      "url": "https://api.testnet.lnmarkets.com/v1"
    }
  ],
  "tags": [
    {
      "name": "Login",
      "description": "Here you can find the different way to auth yourself on LN Markets, mostly use for browser."
    },
    {
      "name": "Futures",
      "description": "Interactions with the futures market and retrive your positions"
    },
    {
      "name": "User",
      "description": "You can retrieve your user data and modify it"
    },
    {
      "name": "State",
      "description": "LN Markets state with data about our node and api availability"
    },
    {
      "name": "LNURL",
      "description": "Interaction with the lightning network using the [LNURL procotocol](https://github.com/btcontract/lnurl-rfc/)\nLNURL enable simple auth, withdraw and pay UX / UI\n"
    }
  ],
  "security": [
    {
      "apiKeyAuth": []
    }
  ],
  "components": {
    "securitySchemes": {
      "apiKeyAuth": {
        "description": "Api key auth is using `LNM-ACCESS-KEY` `LNM-ACCESS-PASSPHRASE` `LNM-ACCESS-TIMESTAMP` `LNM-ACCESS-SIGN` headers",
        "type": "apiKey",
        "in": "header",
        "name": "LNM-ACCESS-KEY"
      }
    }
  },
  "paths": {
    "/login/token": {
      "post": {
        "tags": [
          "Login"
        ],
        "security": [],
        "deprecated": false,
        "summary": "Login with a JWT",
        "description": "Use a JWT to log on LN Markets.\nThe token need to have the 'user' scope and the token will be revoked ater the sucessfull login\n",
        "operationId": "V1_Login_loginCredentials"
      }
    },
    "/lnurl/auth": {
      "get": {
        "tags": [
          "LNURL"
        ],
        "security": [],
        "deprecated": false,
        "summary": "Auth Verify",
        "description": "Verify the public key with the signature and the k1 to create a account or connect into a existing account.\nIf JWT is set to true, a JWT will be returned with by default all scopes and an expiry of 1h, they can be changed by setting the query paramater expiry or scopes like POST /user/jwt.\nElse the connected state will be push over websocketsto the client.\n",
        "operationId": "V1_GET_LNURL_Auth"
      },
      "post": {
        "tags": [
          "LNURL"
        ],
        "security": [],
        "deprecated": false,
        "summary": "Auth Request",
        "description": "LNURL string used to create an account or connect to a existing account.\nThe user wallet will sign a message using the provided k1 inside the LNURL.\nYou need to have a session cookie on the browser you are using to log in.\n",
        "operationId": "V1_POST_LNURL_Auth"
      }
    },
    "/lnurl/withdraw": {
      "get": {
        "tags": [
          "LNURL"
        ],
        "security": [],
        "deprecated": false,
        "summary": "Withdraw (3) Final",
        "description": "Use LNURL to withdraw from the user balance.",
        "operationId": "V1_LNURL_Withdraw"
      },
      "post": {
        "tags": [
          "LNURL"
        ],
        "security": [],
        "deprecated": false,
        "summary": "Withdraw (1) Create",
        "description": "Create a LNURL Withdraw",
        "operationId": "V1_POST_LNURL_withdraw"
      }
    },
    "/lnurl/withdraw/request": {
      "get": {
        "tags": [
          "LNURL"
        ],
        "security": [],
        "deprecated": false,
        "summary": "Withdraw (2) Request",
        "description": "Ask the Lightning wallet to create an invoice with amount and description.",
        "operationId": "V1_LNURL_WithdrawRequest"
      }
    },
    "/lnurl/withdraw/address": {
      "get": {
        "tags": [
          "LNURL"
        ],
        "security": [],
        "deprecated": false,
        "summary": "Withdraw to Lightning Address",
        "description": "Use Lightning Address to withdraw your sat !",
        "operationId": "V1_LNURL_Withdraw_Address"
      }
    },
    "/lnurl/pay": {
      "post": {
        "tags": [
          "LNURL"
        ],
        "security": [],
        "deprecated": false,
        "summary": "Pay (1) Create",
        "description": "Create a LNURL Pay",
        "operationId": "V1_POST_LNURL_pay"
      },
      "get": {
        "tags": [
          "LNURL"
        ],
        "security": [],
        "deprecated": false,
        "summary": "Pay (3) Finalize",
        "description": "LNURL Pay",
        "operationId": "V1_LNURL_Pay"
      }
    },
    "/lnurl/pay/request": {
      "get": {
        "tags": [
          "LNURL"
        ],
        "security": [],
        "deprecated": false,
        "summary": "Pay (1) Request",
        "description": "Response from the LNURL",
        "operationId": "V1_LNURL_PayRequest"
      }
    },
    "/lnurl/pay/address": {
      "get": {
        "tags": [
          "LNURL"
        ],
        "security": [],
        "deprecated": false,
        "summary": "Lightning Address",
        "description": "Lightning Address",
        "operationId": "V1_Lightning_Address"
      }
    },
    "/futures": {
      "post": {
        "tags": [
          "Futures"
        ],
        "security": [
          {
            "apiKeyAuth": [
              "positions_create"
            ]
          }
        ],
        "deprecated": false,
        "summary": "Create",
        "description": "Send the order form parameters to add a new position in database.\n**If `type=\"l\"`, the property `price` must be included in the request to know when the position should be filled.**\n**You can choose to use the margin or the quantity as a parameter, the other will be calculated with the one you choosed**\n",
        "operationId": "V1_Futures_createPosition"
      },
      "put": {
        "tags": [
          "Futures"
        ],
        "security": [
          {
            "apiKeyAuth": [
              "positions_modify"
            ]
          }
        ],
        "deprecated": false,
        "summary": "Update",
        "description": "Allows user to modify `stoploss` or `takeprofit` parameters of an existing position.\n",
        "operationId": "V1_Futures_updatePosition"
      },
      "delete": {
        "tags": [
          "Futures"
        ],
        "security": [
          {
            "apiKeyAuth": [
              "positions_close"
            ]
          }
        ],
        "deprecated": false,
        "summary": "Close",
        "description": "Close the user position, the PL will be calculated against the current bid or offer\ndepending on the side of the position\n",
        "operationId": "V1_Futures_closePosition"
      },
      "get": {
        "tags": [
          "Futures"
        ],
        "security": [
          {
            "apiKeyAuth": [
              "positions_get_open",
              "positions_get_closed"
            ]
          }
        ],
        "deprecated": false,
        "summary": "History",
        "description": "Fetch users positions",
        "operationId": "V1_Futures_getPositionList"
      }
    },
    "/futures/history/index": {
      "get": {
        "tags": [
          "Futures"
        ],
        "security": [],
        "summary": "Futures index history",
        "description": "Retrieves index history at most 1000 entries between two given timestamps.",
        "operationId": "V1_Futures_History_Index"
      }
    },
    "/futures/history/bid-offer": {
      "get": {
        "tags": [
          "Futures"
        ],
        "security": [],
        "summary": "Futures bid and offer history",
        "description": "Retrieves bid and offer at most 1000 entries between two given timestamps.",
        "operationId": "V1_Futures_History_Bid_Offer"
      }
    },
    "/futures/history/fixing": {
      "get": {
        "tags": [
          "Futures"
        ],
        "security": [],
        "summary": "Futures fixing history",
        "description": "Retrieves at most 1000 entries between two given timestamps",
        "operationId": "V1_Futures_History_Fixing"
      }
    },
    "/futures/cancel": {
      "post": {
        "tags": [
          "Futures"
        ],
        "security": [
          {
            "apiKeyAuth": [
              "positions_close"
            ]
          }
        ],
        "deprecated": false,
        "summary": "Cancel",
        "description": "Cancel the position linked to the given `pid`.**Only works on positions that are not currently filled**.\n",
        "operationId": "V1_Futures_cancelPosition"
      }
    },
    "/futures/cash-in": {
      "post": {
        "tags": [
          "Futures"
        ],
        "security": [
          {
            "apiKeyAuth": [
              "positions_modify"
            ]
          }
        ],
        "deprecated": false,
        "summary": "Cash-in",
        "description": "Retrieves part of one running position's PL.\n",
        "operationId": "V1_Futures_cashin"
      }
    },
    "/futures/add-margin": {
      "post": {
        "tags": [
          "Futures"
        ],
        "security": [
          {
            "apiKeyAuth": [
              "positions_modify"
            ]
          }
        ],
        "deprecated": false,
        "summary": "Add margin",
        "description": "Add margin to a running position.",
        "operationId": "V1_Futures_addmargin"
      }
    },
    "/futures/all/close": {
      "delete": {
        "tags": [
          "Futures"
        ],
        "security": [
          {
            "apiKeyAuth": [
              "positions_close"
            ]
          }
        ],
        "deprecated": false,
        "summary": "Close-all",
        "description": "Close every user position. The PL will be calculated against the current bid or offer\ndepending on the side of the position.\n",
        "operationId": "V1_Futures_closeAllPosition"
      }
    },
    "/futures/all/cancel": {
      "delete": {
        "tags": [
          "Futures"
        ],
        "security": [
          {
            "apiKeyAuth": [
              "positions_close"
            ]
          }
        ],
        "deprecated": false,
        "summary": "Cancel-all",
        "description": "Cancel all open positions",
        "operationId": "V1_Futures_cancelAllPosition"
      }
    },
    "/futures/leaderboard": {
      "get": {
        "tags": [
          "State"
        ],
        "security": [],
        "deprecated": false,
        "summary": "Leaderboard",
        "description": "Queries the database to get the 10 users with the biggest posititve PL\n",
        "operationId": "V1_Leaderboard_getLeaderboard"
      }
    },
    "/futures/carry-fees": {
      "get": {
        "tags": [
          "Futures"
        ],
        "security": [
          {
            "apiKeyAuth": [
              "positions_get_closed"
            ]
          }
        ],
        "summary": "Futures carry fees history",
        "description": "Retrieves carry fees for user",
        "operationId": "V1_Futures_Carry_Fees"
      }
    },
    "/state": {
      "get": {
        "tags": [
          "State"
        ],
        "security": [],
        "deprecated": false,
        "summary": "API",
        "description": "Shows informations about api.\n",
        "operationId": "V1_State_apiState"
      }
    },
    "/state/node": {
      "get": {
        "tags": [
          "State"
        ],
        "security": [],
        "deprecated": false,
        "summary": "Node",
        "description": "Shows informations about the lightning node.\n",
        "operationId": "V1_State_nodeState"
      }
    },
    "/state/announcements": {
      "get": {
        "tags": [
          "State"
        ],
        "security": [],
        "deprecated": false,
        "summary": "Announcements",
        "description": "Get the list of LN Markets announcements\n",
        "operationId": "V1_Announcements_getAnnouncements"
      }
    },
    "/user": {
      "get": {
        "tags": [
          "User"
        ],
        "security": [
          {
            "apiKeyAuth": [
              "user_get"
            ]
          }
        ],
        "deprecated": false,
        "summary": "Informations",
        "description": "Get the user account Information",
        "operationId": "V1_User_getUser"
      },
      "put": {
        "tags": [
          "User"
        ],
        "security": [
          {
            "apiKeyAuth": [
              "user_modify"
            ]
          }
        ],
        "deprecated": false,
        "summary": "Update user",
        "description": "Modifies account parameters",
        "operationId": "V1_User_updateUser"
      }
    },
    "/user/deposit": {
      "post": {
        "tags": [
          "User"
        ],
        "security": [
          {
            "apiKeyAuth": [
              "wallet_deposit"
            ]
          }
        ],
        "deprecated": false,
        "summary": "Deposit",
        "description": "Add fund to your LN Markets balance",
        "operationId": "V1_User_deposit"
      },
      "get": {
        "tags": [
          "User"
        ],
        "security": [
          {
            "apiKeyAuth": [
              "wallet_deposit"
            ]
          }
        ],
        "deprecated": false,
        "summary": "Deposit History",
        "description": "Get deposit history",
        "operationId": "V1_User_getDepositHistory"
      }
    },
    "/user/withdraw": {
      "post": {
        "tags": [
          "User"
        ],
        "security": [
          {
            "apiKeyAuth": [
              "wallet_withdraw"
            ]
          }
        ],
        "summary": "Withdraw via invoice",
        "description": "Withdraw from LN Markets with a Lightning Invoice",
        "operationId": "V1_User_Withdraw"
      },
      "get": {
        "tags": [
          "User"
        ],
        "security": [
          {
            "apiKeyAuth": [
              "wallet_withdraw"
            ]
          }
        ],
        "deprecated": false,
        "summary": "Withdraw History",
        "description": "Ge withdraw history\n",
        "operationId": "V1_User_getWithdrawHistory"
      }
    }
  }
}
