openapi: '3.0.3'

info:
  title: API
  description: |
    Trade derivatives on the **[Lightning Network](https://lightning.network/)**.
    You can find our website **[here](https://lnmarkets.com/)**.
  version: '1.0.0'

servers:
  - description: Mainnet API
    url: https://api.lnmarkets.com/v1
  - description: Testnet API
    url: https://api.testnet.lnmarkets.com/v1

tags:
  - name: Login
    description: |
      Here you can find the different way to auth yourself on LN Markets, mostly use for browser.

  - name: Futures
    description: Interactions with the futures market and retrive your positions

  - name: User
    description: |
      You can retrieve your user data and modify it

  - name: State
    description: |
      LN Markets state with data about our node and api availability

  - name: LNURL
    description: |
      Interaction with the lightning network using the [LNURL procotocol](https://github.com/btcontract/lnurl-rfc/)
      LNURL enable simple auth process and easier withdraw

security:
  - cookieAuth: []
  - jwtAuth: []

paths:
  '/login/credentials':
    post:
      $ref: 'paths/login/credentials/post.yaml'

  '/login/credentials/create':
    post:
      $ref: 'paths/login/credentials/create/post.yaml'

  '/login/token':
    post:
      $ref: 'paths/login/token/post.yaml'

  '/login/credentials/reset':
    post:
      $ref: 'paths/login/credentials/reset/post.yaml'
    put:
      $ref: 'paths/login/credentials/reset/put.yaml'

  '/lnurl/auth':
    get:
      $ref: 'paths/lnurl/auth/get.yaml'
    post:
      $ref: 'paths/lnurl/auth/post.yaml'

  '/lnurl/withdraw':
    get:
      $ref: 'paths/lnurl/withdraw/get.yaml'
    post:
      $ref: 'paths/lnurl/withdraw/post.yaml'

  '/lnurl/withdraw/request':
    get:
      $ref: 'paths/lnurl/withdraw/request/get.yaml'

  '/login/joule':
    post:
      $ref: 'paths/login/joule/post.yaml'
    get:
      $ref: 'paths/login/joule/get.yaml'

  '/futures':
    post:
      $ref: 'paths/futures/post.yaml'
    put:
      $ref: 'paths/futures/put.yaml'
    delete:
      $ref: 'paths/futures/delete.yaml'
    get:
      $ref: 'paths/futures/get.yaml'

  '/futures/history':
    get:
      $ref: 'paths/futures/history/get.yaml'

  '/futures/cancel':
    post:
      $ref: 'paths/futures/cancel/post.yaml'

  '/futures/cash-in':
    post:
      $ref: 'paths/futures/cash-in/post.yaml'

  '/futures/add-margin':
    post:
      $ref: 'paths/futures/add-margin/post.yaml'

  '/futures/all/close':
    delete:
      $ref: 'paths/futures/all/close/delete.yaml'

  '/futures/all/cancel':
    delete:
      $ref: 'paths/futures/all/cancel/delete.yaml'

  '/state':
    get:
      $ref: 'paths/state/get.yaml'

  '/state/node':
    get:
      $ref: 'paths/state/node/get.yaml'

  '/state/leaderboard':
    get:
      $ref: 'paths/state/leaderboard/get.yaml'

  '/state/announcements':
    get:
      $ref: 'paths/state/announcements/get.yaml'

  '/user':
    get:
      $ref: 'paths/user/get.yaml'
    put:
      $ref: 'paths/user/put.yaml'

  '/user/update-password':
    put:
      $ref: 'paths/user/update-password/put.yaml'

  '/user/jwt':
    get:
      $ref: 'paths/user/jwt/get.yaml'
    delete:
      $ref: 'paths/user/jwt/delete.yaml'
    post:
      $ref: 'paths/user/jwt/post.yaml'

  '/user/deposit':
    post:
      $ref: 'paths/user/deposit/post.yaml'
    get:
      $ref: 'paths/user/deposit/get.yaml'

  '/user/withdraw':
    post:
      $ref: 'paths/user/withdraw/post.yaml'
    get:
      $ref: 'paths/user/withdraw/get.yaml'

  '/user/logout':
    post:
      $ref: 'paths/user/logout/post.yaml'

  '/user/email-confirm':
    put:
      $ref: 'paths/user/email-confirm/put.yaml'

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: session

    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
