name: Build

on:
  push:
    branches: [api-v1]

jobs:
  node:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6

      - name: Install
        run: pnpm install --frozen-lockfile --ignore-script

      - name: Run index.js
        run: node index.js

      - name: Build Redoc
        run: ./scripts/build.sh

      - name: Upload the build artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: ./build

  gh-pages:
    name: Github Pages
    runs-on: ubuntu-latest
    needs: [node]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: build
          path: ./build

      - name: Deploy api docs 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: build
          target-folder: api/v1
