name: Pull request

on:
  pull_request:
    branches: [api-v1]

jobs:
  node:
    name: Node
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6

      - name: Install
        run: pnpm install --frozen-lockfile --ignore-script

      - name: Run index.js
        run: node index.js

      - name: Build Redoc
        run: ./scripts/build.sh
