name: Pull request

on:
  pull_request:
    branches: [api-v1]

jobs:
  node:
    name: Node
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Cache Node.js modules
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Yarn install
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile --prefer-offline

      - name: Run index.js
        run: node index.js

      - name: Upload the build artifact
        uses: actions/upload-artifact@v2
        with:
          name: _api.md
          path: ./_api.md

      - name: Upload the dist artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: ./dist

  slate:
    name: Slate
    runs-on: ubuntu-latest
    needs: node

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Download _api.md
        uses: actions/download-artifact@v2
        with:
          name: _api.md

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true
          working-directory: ./slate

      - name: Install gem
        run: bundle install
        working-directory: ./slate

      - name: Build slate
        run: ./scripts/build.sh

      - name: Upload the build artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: ./build
